--------------------------------------------------------
-- Archivo creado  - martes-agosto-06-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAZAS
--------------------------------------------------------

  CREATE TABLE "ADMPROC"."PLAZAS" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"EXTENSION" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"ESTADO" NUMBER(3,0) DEFAULT '1'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA" ;
REM INSERTING into ADMPROC.PLAZAS
SET DEFINE OFF;
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (5,'40','.040',1);
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (6,'50','.050',1);
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (7,'Sonora','.065',1);
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (4,'10','.010',1);
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (1,'60','.060',1);
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (2,'30','.030',1);
Insert into ADMPROC.PLAZAS (ID,NOMBRE,EXTENSION,ESTADO) values (3,'20','.020',1);
--------------------------------------------------------
--  DDL for Index SYS_C00103273
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMPROC"."SYS_C00103273" ON "ADMPROC"."PLAZAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA" ;
--------------------------------------------------------
--  Constraints for Table PLAZAS
--------------------------------------------------------

  ALTER TABLE "ADMPROC"."PLAZAS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMPROC"."PLAZAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLAZAS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMPROC"."PLAZAS_SEQ_TR" 
 BEFORE INSERT ON PLAZAS FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN
 SELECT PLAZAS_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;

/
ALTER TRIGGER "ADMPROC"."PLAZAS_SEQ_TR" ENABLE;
