--------------------------------------------------------
-- Archivo creado  - martes-agosto-06-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROCESOS
--------------------------------------------------------

  CREATE TABLE "ADMPROC"."PROCESOS" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"PREFIJO" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"PLAZA" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"PATH_DIR" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"FILENAME" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"HEADER_TIENDA" VARCHAR2(20 BYTE) DEFAULT '0', 
	"LONGITUD_HT" NUMBER(10,0) DEFAULT '0', 
	"HEADER_RECEPCION" VARCHAR2(20 BYTE) DEFAULT '1200', 
	"LONGITUD_HR" NUMBER(10,0) DEFAULT '0', 
	"ARTICULO" VARCHAR2(20 BYTE) DEFAULT '1212', 
	"LONGITUD_ARTICULO" NUMBER(10,0) DEFAULT '0', 
	"LINEAS_MINIMAS" NUMBER(10,0) DEFAULT '0', 
	"SOFTERROR" NUMBER(3,0) DEFAULT '0', 
	"PATH_PROCESADOS" VARCHAR2(250 BYTE) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA" ;
REM INSERTING into ADMPROC.PROCESOS
SET DEFINE OFF;
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (5,'Cambios de Precio','CambioPrecio_','\.(\d\d\d)','\\132.148.160.202\workarea\MOV_INVENTARIOS\CAMBIOSPRECIO\PATest','^NCP_(\d\d\d\d)(\d\d)(\d\d)_(\d\d\d\d)\.(\d\d\d)$','^0000',17,'^2000',20,'^2001',55,0,1,'\\132.148.160.202\workarea\MOV_INVENTARIOS\CAMBIOSPRECIO\PATest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (6,'Mercancia Especial','MercanciaEsp_','\.(\d\d\d)','\\132.148.160.202\workarea\Contabilidad\TFMERCANCIA\PATest','^M(\d\d\d\d)(\d\d\d\d)(\d\d)(\d\d)\.(\d\d\d)$','^0000',17,'^1400',16,'^1412',52,0,1,'\\132.148.160.202\workarea\Contabilidad\TFMERCANCIA\PATest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (7,'Transferencias','Transferencias_','\.(\d\d\d)','\\132.148.160.202\workarea\MOV_INVENTARIOS\TRANSFERENCIAS\PATest','^TRANSF_(\d\d\d\d)(\d\d)(\d\d)_(\d\d\d\d).(\d\d\d)','^0000',17,'^2400',39,'^2403',53,0,1,'\\132.148.160.202\workarea\MOV_INVENTARIOS\TRANSFERENCIAS\PATest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (8,'Merma','Merma_','\.(\d\d\d)','\\132.148.160.202\workarea\Contabilidad\BACKMERMA\PATest','^MU(\d\d)(\d\d\d\d)(\d\d)(\d\d).(\d\d\d)','^0000',17,'^2000',20,'^2001',55,0,1,'\\132.148.160.202\workarea\Contabilidad\BACKMERMA\PATest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (1,'Recepcion sin Pedido','RECEPRSO_','\.(\d\d\d)','\\132.148.160.202\workarea\Contabilidad\RECEPRSO\PATest','^MC(\d\d)(\d\d)(\d\d)(\d\d\d\d\d)\.(\d\d\d)$','^0000',17,'^1200',97,'^1212',52,0,1,'\\132.148.160.202\workarea\Contabilidad\RECEPRSO\PATest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (2,'Recepcion CDC','RECEPCDC_','\.(\d\d\d)','\\10.160.1.100\d_workarea\SICS\Contabilidad\back\PAtest','^MC(\d\d)(\d\d)(\d\d\d\d)(\d\d\d\d)\.(\d\d\d)$','^0000',17,'^1200',97,'^1212',52,0,1,'\\10.160.1.100\d_workarea\SICS\Contabilidad\back\PAtest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (3,'Notas de Credito','NotasCredito_','\.(\d\d\d)','\\132.148.160.202\workarea\MOV_INVENTARIOS\NOTASCREDITO\PATest','^NCR_(\d\d\d\d)(\d\d)(\d\d)_(\d\d\d\d)\.(\d\d\d)$','^0000',17,'^1200',97,'^1212',52,0,1,'\\132.148.160.202\workarea\MOV_INVENTARIOS\NOTASCREDITO\PATest\procesados');
Insert into ADMPROC.PROCESOS (ID,NOMBRE,PREFIJO,PLAZA,PATH_DIR,FILENAME,HEADER_TIENDA,LONGITUD_HT,HEADER_RECEPCION,LONGITUD_HR,ARTICULO,LONGITUD_ARTICULO,LINEAS_MINIMAS,SOFTERROR,PATH_PROCESADOS) values (4,'Caratulas de Inventario','CaratulasInv_','\.(\d\d\d)','\\132.148.160.202\workarea\Contabilidad\back\PATest','^M(\d\d\d\d)(\d\d\d\d)(\d\d)(\d\d)\.(\d\d\d)$','^0000',17,'^1400',16,'^1412',52,0,1,'\\132.148.160.202\workarea\Contabilidad\back\PATest\procesados');
--------------------------------------------------------
--  DDL for Index SYS_C00103278
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMPROC"."SYS_C00103278" ON "ADMPROC"."PROCESOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA" ;
--------------------------------------------------------
--  Constraints for Table PROCESOS
--------------------------------------------------------

  ALTER TABLE "ADMPROC"."PROCESOS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMPROC"."PROCESOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROCESOS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMPROC"."PROCESOS_SEQ_TR" 
 BEFORE INSERT ON PROCESOS FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN
 SELECT PROCESOS_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;

/
ALTER TRIGGER "ADMPROC"."PROCESOS_SEQ_TR" ENABLE;
