--------------------------------------------------------
-- Archivo creado  - martes-agosto-06-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROCESADOS_ERROR
--------------------------------------------------------

  CREATE TABLE "ADMPROC"."PROCESADOS_ERROR" 
   (	"ID" NUMBER(10,0), 
	"PROCESO_ID" NUMBER(10,0), 
	"PROCESO_NOMBRE" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"PLAZA" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"NOMBRE_ARCHIVO" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"FECHA" DATE DEFAULT NULL, 
	"HEADER_TIENDA" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"HEADER_RECEPCION" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"ARTICULO" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"ERRORES_HEADER_TIENDA" NUMBER(10,0) DEFAULT NULL, 
	"ERRORES_HEADER_RECEPCION" NUMBER(10,0) DEFAULT NULL, 
	"ERRORES_ARTICULO" NUMBER(10,0) DEFAULT NULL, 
	"PLAZA_ID" NUMBER(10,0) DEFAULT NULL
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA" ;
REM INSERTING into ADMPROC.PROCESADOS_ERROR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C00103276
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMPROC"."SYS_C00103276" ON "ADMPROC"."PROCESADOS_ERROR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA" ;
--------------------------------------------------------
--  Constraints for Table PROCESADOS_ERROR
--------------------------------------------------------

  ALTER TABLE "ADMPROC"."PROCESADOS_ERROR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMPROC"."PROCESADOS_ERROR" MODIFY ("PROCESO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ADMPROC"."PROCESADOS_ERROR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ADMPROC_DATA"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROCESADOS_ERROR_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMPROC"."PROCESADOS_ERROR_SEQ_TR" 
 BEFORE INSERT ON PROCESADOS_error FOR EACH ROW  WHEN (NEW.id IS NULL) BEGIN
 SELECT PROCESADOS_error_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;

/
ALTER TRIGGER "ADMPROC"."PROCESADOS_ERROR_SEQ_TR" ENABLE;
